### ISSUE TITLE
Not loading on latest version of Chrome

### ISSUE THREAD

**Issue by juleswz** [maltoze/sgreen#4]
Hi,

I love Sgreen, it's just doing exactly what i need, but sadly since last update of Chrome on MacOS (Version 130.0.6723.70 (Build officiel) (arm64) it's not working anymore. A co-worker using it on Windows has the same problem.

Here's the error message i get in Chrome's console : 

> Refused to load the script 'chrome-extension://e4aae688-ef77-4ad3-b5a4-1d879494bdc7/assets/src/entries/contentScript/primary/main-bb129543.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Hope this will help you fix this issue.

**Comment by maltoze** [comment]
fixed

**Comment by juleswz** [comment]
Great, thanks !
